format: "\
  {{.directory}}\
  {{.git_branch}}\
  {{.golang}}\
  {{.time}}{{.line_break}}\
  {{.character}}"

directory:
  format: "[{{.symbol}}<fg=2196f3>{{.path}}</>] "
  symbol: " "
  disabled: false

git_branch:
  format: "[{{.symbol}}<fg=2196f3>{{.git_branch}}</>] "
  symbol: " "
  disabled: false

time:
  format: "[{{.symbol}}<fg=2196f3>{{.time}}</>] "
  symbol: " "
  disabled: false

golang:
  format: "[{{.symbol}}<fg=2196f3>v{{.version}}</>] "
  symbol: " "
  disabled: false

character:
  format: " "
  disabled: false

continuation:
  format: " "
  disabled: false
